name: "Hello Action"
description: "Une action simple pour GitHub"
author: "Rafal"
input:
  name:
    description: "Nom de l'utilisateur"
    required: true
    default: "World"
runs:
  using: "node20"
  main: "index.js"

branding:
  icon: 'message-square'
  color: 'blue'